---
platforms:
  - name: instance
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
---

dependency:

  name: galaxy

driver:

  name: docker

lint: |

  set -e

  yamllint .

  ansible-lint

platforms:

  - name: instance

    image: geerlingguy/docker-centos7-ansible:latest

    command: ""

    volumes:

      - /sys/fs/cgroup:/sys/fs/cgroup:rw

      - /var/lib/containerd

    cgroupns_mode: host

    privileged: true

    pre_build_image: true

provisioner:

  name: ansible

verifier:

  name: ansible
